### ISSUE TITLE
Add a Mech-building Validation page

### ISSUE THREAD

**Issue by infinitymdm** [mechtronica/mechtronica.net#22]
Add a page that walks players through the process of calculating mech stats and making sure their build works as intended.

- [x] Validating
    - [x] Calculating mech stats
    - [x] What to do if your stats don't work out
    - [x] Tips and tricks for tuning, such as making use of Equipment or Modules to even out stat imbalances

**Comment by Icosahunter** [comment]
This issue is addressed in [2b49e54](https://github.com/mechtronica/mechtronica.net/commit/2b49e546372a8b4451ebc5f6d7f69d7ae363a319). @infinitymdm if you think the validation page added there is sufficient we can close this.

**Comment by infinitymdm** [comment]
Looks to me as though you've addressed the first item in the issue description, but not the other two. I'll leave it to you to make the call of whether those other two items are worth including.
