### ISSUE TITLE
Add "How to Play Guide" Section or Page

### ISSUE THREAD

**Issue by Icosahunter** [mechtronica/mechtronica.net#54]
To introduce new players to the basic concepts so the rules reference makes sense.

**Comment by infinitymdm** [comment]
Page ideas:

- How to be a good player (intro to TTRPGs specifically focused on Mechtronica)
- How to be a good GM (session structure, cadence of a campaign, how to help players build their mechs during 1st session, etc.)

**Comment by Icosahunter** [comment]
Done as of merge #73

**Comment by Icosahunter** [comment]
Done as of merge #73
