### ISSUE TITLE
Add some simple "Out of Mech" play rules

### ISSUE THREAD

**Issue by Icosahunter** [mechtronica/mechtronica.net#56]
- [x] Hand-to-hand combat rules
- [ ] (Add more stuff here?)

**Comment by infinitymdm** [comment]
I'll work on out-of-mech combat rules based on the old "Opportunity Points" mechanic we discussed on discord, with each turn consisting of movement + one action (stat roll).

**Comment by infinitymdm** [comment]
Duplicate of #57
