### ISSUE TITLE
Add rules for how battling creatures work

### ISSUE THREAD

**Issue by Icosahunter** [mechtronica/mechtronica.net#63]

**Comment by infinitymdm** [comment]
We've done this in the past with a system where creatures have appendages (much like how mechs have sections), where each appendage may allow the creature to use a special attack. You can break a creature's appendages by depleting the associated health pool. When a creature's appendage is broken, it's no longer able to use any special attacks or abilities from that appendage.

Creature behavior may also be modified by depleting health of certain appendages. We've had creatures that run away once the health of a certain appendage is below a threshold.
